apiVersion: v1
kind: Service
metadata:
  name: auth-service-metrics
  namespace: mtv-erp
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      nodePort: 30080
