// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId      string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurchaseItemId string                 `protobuf:"bytes,3,opt,name=purchase_item_id,json=purchaseItemId,proto3" json:"purchase_item_id,omitempty"`
	Safra          string                 `protobuf:"bytes,4,opt,name=safra,proto3" json:"safra,omitempty"`
	QuantityKg     string                 `protobuf:"bytes,5,opt,name=quantity_kg,json=quantityKg,proto3" json:"quantity_kg,omitempty"`
	ReceivedAt     string                 `protobuf:"bytes,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Lot) Reset() {
	*x = Lot{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lot) ProtoMessage() {}

func (x *Lot) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lot.ProtoReflect.Descriptor instead.
func (*Lot) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Lot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lot) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Lot) GetPurchaseItemId() string {
	if x != nil {
		return x.PurchaseItemId
	}
	return ""
}

func (x *Lot) GetSafra() string {
	if x != nil {
		return x.Safra
	}
	return ""
}

func (x *Lot) GetQuantityKg() string {
	if x != nil {
		return x.QuantityKg
	}
	return ""
}

func (x *Lot) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

type CreateLotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurchaseItemId string                 `protobuf:"bytes,2,opt,name=purchase_item_id,json=purchaseItemId,proto3" json:"purchase_item_id,omitempty"`
	Safra          string                 `protobuf:"bytes,3,opt,name=safra,proto3" json:"safra,omitempty"`
	QuantityKg     string                 `protobuf:"bytes,4,opt,name=quantity_kg,json=quantityKg,proto3" json:"quantity_kg,omitempty"`
	ReceivedAt     string                 `protobuf:"bytes,5,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLotRequest) Reset() {
	*x = CreateLotRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLotRequest) ProtoMessage() {}

func (x *CreateLotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLotRequest.ProtoReflect.Descriptor instead.
func (*CreateLotRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLotRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateLotRequest) GetPurchaseItemId() string {
	if x != nil {
		return x.PurchaseItemId
	}
	return ""
}

func (x *CreateLotRequest) GetSafra() string {
	if x != nil {
		return x.Safra
	}
	return ""
}

func (x *CreateLotRequest) GetQuantityKg() string {
	if x != nil {
		return x.QuantityKg
	}
	return ""
}

func (x *CreateLotRequest) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

type CreateLotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lot           *Lot                   `protobuf:"bytes,1,opt,name=lot,proto3" json:"lot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLotResponse) Reset() {
	*x = CreateLotResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLotResponse) ProtoMessage() {}

func (x *CreateLotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLotResponse.ProtoReflect.Descriptor instead.
func (*CreateLotResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLotResponse) GetLot() *Lot {
	if x != nil {
		return x.Lot
	}
	return nil
}

type StockMovement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LotId         string                 `protobuf:"bytes,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	QuantityKg    string                 `protobuf:"bytes,4,opt,name=quantity_kg,json=quantityKg,proto3" json:"quantity_kg,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Origin        string                 `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockMovement) Reset() {
	*x = StockMovement{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockMovement) ProtoMessage() {}

func (x *StockMovement) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockMovement.ProtoReflect.Descriptor instead.
func (*StockMovement) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *StockMovement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StockMovement) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *StockMovement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StockMovement) GetQuantityKg() string {
	if x != nil {
		return x.QuantityKg
	}
	return ""
}

func (x *StockMovement) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *StockMovement) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type RegisterMovementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotId         string                 `protobuf:"bytes,1,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	QuantityKg    string                 `protobuf:"bytes,3,opt,name=quantity_kg,json=quantityKg,proto3" json:"quantity_kg,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMovementRequest) Reset() {
	*x = RegisterMovementRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMovementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMovementRequest) ProtoMessage() {}

func (x *RegisterMovementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMovementRequest.ProtoReflect.Descriptor instead.
func (*RegisterMovementRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterMovementRequest) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *RegisterMovementRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisterMovementRequest) GetQuantityKg() string {
	if x != nil {
		return x.QuantityKg
	}
	return ""
}

func (x *RegisterMovementRequest) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *RegisterMovementRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type RegisterMovementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movement      *StockMovement         `protobuf:"bytes,1,opt,name=movement,proto3" json:"movement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMovementResponse) Reset() {
	*x = RegisterMovementResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMovementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMovementResponse) ProtoMessage() {}

func (x *RegisterMovementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMovementResponse.ProtoReflect.Descriptor instead.
func (*RegisterMovementResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterMovementResponse) GetMovement() *StockMovement {
	if x != nil {
		return x.Movement
	}
	return nil
}

type GetStockByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockByProductRequest) Reset() {
	*x = GetStockByProductRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockByProductRequest) ProtoMessage() {}

func (x *GetStockByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockByProductRequest.ProtoReflect.Descriptor instead.
func (*GetStockByProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockByProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetStockByProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalKg       string                 `protobuf:"bytes,1,opt,name=total_kg,json=totalKg,proto3" json:"total_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockByProductResponse) Reset() {
	*x = GetStockByProductResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockByProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockByProductResponse) ProtoMessage() {}

func (x *GetStockByProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockByProductResponse.ProtoReflect.Descriptor instead.
func (*GetStockByProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockByProductResponse) GetTotalKg() string {
	if x != nil {
		return x.TotalKg
	}
	return ""
}

type GetLotDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotId         string                 `protobuf:"bytes,1,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLotDetailsRequest) Reset() {
	*x = GetLotDetailsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotDetailsRequest) ProtoMessage() {}

func (x *GetLotDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetLotDetailsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *GetLotDetailsRequest) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

type GetLotDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lot           *Lot                   `protobuf:"bytes,1,opt,name=lot,proto3" json:"lot,omitempty"`
	Movements     []*StockMovement       `protobuf:"bytes,2,rep,name=movements,proto3" json:"movements,omitempty"`
	BalanceKg     string                 `protobuf:"bytes,3,opt,name=balance_kg,json=balanceKg,proto3" json:"balance_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLotDetailsResponse) Reset() {
	*x = GetLotDetailsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotDetailsResponse) ProtoMessage() {}

func (x *GetLotDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetLotDetailsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *GetLotDetailsResponse) GetLot() *Lot {
	if x != nil {
		return x.Lot
	}
	return nil
}

func (x *GetLotDetailsResponse) GetMovements() []*StockMovement {
	if x != nil {
		return x.Movements
	}
	return nil
}

func (x *GetLotDetailsResponse) GetBalanceKg() string {
	if x != nil {
		return x.BalanceKg
	}
	return ""
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\"\xb6\x01\n" +
	"\x03Lot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12(\n" +
	"\x10purchase_item_id\x18\x03 \x01(\tR\x0epurchaseItemId\x12\x14\n" +
	"\x05safra\x18\x04 \x01(\tR\x05safra\x12\x1f\n" +
	"\vquantity_kg\x18\x05 \x01(\tR\n" +
	"quantityKg\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\tR\n" +
	"receivedAt\"\xb3\x01\n" +
	"\x10CreateLotRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12(\n" +
	"\x10purchase_item_id\x18\x02 \x01(\tR\x0epurchaseItemId\x12\x14\n" +
	"\x05safra\x18\x03 \x01(\tR\x05safra\x12\x1f\n" +
	"\vquantity_kg\x18\x04 \x01(\tR\n" +
	"quantityKg\x12\x1f\n" +
	"\vreceived_at\x18\x05 \x01(\tR\n" +
	"receivedAt\"8\n" +
	"\x11CreateLotResponse\x12#\n" +
	"\x03lot\x18\x01 \x01(\v2\x11.inventory.v1.LotR\x03lot\"\xa4\x01\n" +
	"\rStockMovement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06lot_id\x18\x02 \x01(\tR\x05lotId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vquantity_kg\x18\x04 \x01(\tR\n" +
	"quantityKg\x12\x1f\n" +
	"\voccurred_at\x18\x05 \x01(\tR\n" +
	"occurredAt\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\tR\x06origin\"\x9e\x01\n" +
	"\x17RegisterMovementRequest\x12\x15\n" +
	"\x06lot_id\x18\x01 \x01(\tR\x05lotId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vquantity_kg\x18\x03 \x01(\tR\n" +
	"quantityKg\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\tR\n" +
	"occurredAt\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\"S\n" +
	"\x18RegisterMovementResponse\x127\n" +
	"\bmovement\x18\x01 \x01(\v2\x1b.inventory.v1.StockMovementR\bmovement\"9\n" +
	"\x18GetStockByProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"6\n" +
	"\x19GetStockByProductResponse\x12\x19\n" +
	"\btotal_kg\x18\x01 \x01(\tR\atotalKg\"-\n" +
	"\x14GetLotDetailsRequest\x12\x15\n" +
	"\x06lot_id\x18\x01 \x01(\tR\x05lotId\"\x96\x01\n" +
	"\x15GetLotDetailsResponse\x12#\n" +
	"\x03lot\x18\x01 \x01(\v2\x11.inventory.v1.LotR\x03lot\x129\n" +
	"\tmovements\x18\x02 \x03(\v2\x1b.inventory.v1.StockMovementR\tmovements\x12\x1d\n" +
	"\n" +
	"balance_kg\x18\x03 \x01(\tR\tbalanceKg2\x83\x03\n" +
	"\x10InventoryService\x12L\n" +
	"\tCreateLot\x12\x1e.inventory.v1.CreateLotRequest\x1a\x1f.inventory.v1.CreateLotResponse\x12a\n" +
	"\x10RegisterMovement\x12%.inventory.v1.RegisterMovementRequest\x1a&.inventory.v1.RegisterMovementResponse\x12d\n" +
	"\x11GetStockByProduct\x12&.inventory.v1.GetStockByProductRequest\x1a'.inventory.v1.GetStockByProductResponse\x12X\n" +
	"\rGetLotDetails\x12\".inventory.v1.GetLotDetailsRequest\x1a#.inventory.v1.GetLotDetailsResponseB@Z>mtv-erp/inventory-service/internal/pb/inventory/v1;inventoryv1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(*Lot)(nil),                       // 0: inventory.v1.Lot
	(*CreateLotRequest)(nil),          // 1: inventory.v1.CreateLotRequest
	(*CreateLotResponse)(nil),         // 2: inventory.v1.CreateLotResponse
	(*StockMovement)(nil),             // 3: inventory.v1.StockMovement
	(*RegisterMovementRequest)(nil),   // 4: inventory.v1.RegisterMovementRequest
	(*RegisterMovementResponse)(nil),  // 5: inventory.v1.RegisterMovementResponse
	(*GetStockByProductRequest)(nil),  // 6: inventory.v1.GetStockByProductRequest
	(*GetStockByProductResponse)(nil), // 7: inventory.v1.GetStockByProductResponse
	(*GetLotDetailsRequest)(nil),      // 8: inventory.v1.GetLotDetailsRequest
	(*GetLotDetailsResponse)(nil),     // 9: inventory.v1.GetLotDetailsResponse
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.CreateLotResponse.lot:type_name -> inventory.v1.Lot
	3, // 1: inventory.v1.RegisterMovementResponse.movement:type_name -> inventory.v1.StockMovement
	0, // 2: inventory.v1.GetLotDetailsResponse.lot:type_name -> inventory.v1.Lot
	3, // 3: inventory.v1.GetLotDetailsResponse.movements:type_name -> inventory.v1.StockMovement
	1, // 4: inventory.v1.InventoryService.CreateLot:input_type -> inventory.v1.CreateLotRequest
	4, // 5: inventory.v1.InventoryService.RegisterMovement:input_type -> inventory.v1.RegisterMovementRequest
	6, // 6: inventory.v1.InventoryService.GetStockByProduct:input_type -> inventory.v1.GetStockByProductRequest
	8, // 7: inventory.v1.InventoryService.GetLotDetails:input_type -> inventory.v1.GetLotDetailsRequest
	2, // 8: inventory.v1.InventoryService.CreateLot:output_type -> inventory.v1.CreateLotResponse
	5, // 9: inventory.v1.InventoryService.RegisterMovement:output_type -> inventory.v1.RegisterMovementResponse
	7, // 10: inventory.v1.InventoryService.GetStockByProduct:output_type -> inventory.v1.GetStockByProductResponse
	9, // 11: inventory.v1.InventoryService.GetLotDetails:output_type -> inventory.v1.GetLotDetailsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
