// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_CreateLot_FullMethodName         = "/inventory.v1.InventoryService/CreateLot"
	InventoryService_RegisterMovement_FullMethodName  = "/inventory.v1.InventoryService/RegisterMovement"
	InventoryService_GetStockByProduct_FullMethodName = "/inventory.v1.InventoryService/GetStockByProduct"
	InventoryService_GetLotDetails_FullMethodName     = "/inventory.v1.InventoryService/GetLotDetails"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotResponse, error)
	RegisterMovement(ctx context.Context, in *RegisterMovementRequest, opts ...grpc.CallOption) (*RegisterMovementResponse, error)
	GetStockByProduct(ctx context.Context, in *GetStockByProductRequest, opts ...grpc.CallOption) (*GetStockByProductResponse, error)
	GetLotDetails(ctx context.Context, in *GetLotDetailsRequest, opts ...grpc.CallOption) (*GetLotDetailsResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLotResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) RegisterMovement(ctx context.Context, in *RegisterMovementRequest, opts ...grpc.CallOption) (*RegisterMovementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterMovementResponse)
	err := c.cc.Invoke(ctx, InventoryService_RegisterMovement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetStockByProduct(ctx context.Context, in *GetStockByProductRequest, opts ...grpc.CallOption) (*GetStockByProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockByProductResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetStockByProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetLotDetails(ctx context.Context, in *GetLotDetailsRequest, opts ...grpc.CallOption) (*GetLotDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLotDetailsResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetLotDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	CreateLot(context.Context, *CreateLotRequest) (*CreateLotResponse, error)
	RegisterMovement(context.Context, *RegisterMovementRequest) (*RegisterMovementResponse, error)
	GetStockByProduct(context.Context, *GetStockByProductRequest) (*GetStockByProductResponse, error)
	GetLotDetails(context.Context, *GetLotDetailsRequest) (*GetLotDetailsResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) CreateLot(context.Context, *CreateLotRequest) (*CreateLotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLot not implemented")
}
func (UnimplementedInventoryServiceServer) RegisterMovement(context.Context, *RegisterMovementRequest) (*RegisterMovementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterMovement not implemented")
}
func (UnimplementedInventoryServiceServer) GetStockByProduct(context.Context, *GetStockByProductRequest) (*GetStockByProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockByProduct not implemented")
}
func (UnimplementedInventoryServiceServer) GetLotDetails(context.Context, *GetLotDetailsRequest) (*GetLotDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLotDetails not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_CreateLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateLot(ctx, req.(*CreateLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_RegisterMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMovementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).RegisterMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_RegisterMovement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).RegisterMovement(ctx, req.(*RegisterMovementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetStockByProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockByProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetStockByProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetStockByProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetStockByProduct(ctx, req.(*GetStockByProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetLotDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetLotDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetLotDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetLotDetails(ctx, req.(*GetLotDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLot",
			Handler:    _InventoryService_CreateLot_Handler,
		},
		{
			MethodName: "RegisterMovement",
			Handler:    _InventoryService_RegisterMovement_Handler,
		},
		{
			MethodName: "GetStockByProduct",
			Handler:    _InventoryService_GetStockByProduct_Handler,
		},
		{
			MethodName: "GetLotDetails",
			Handler:    _InventoryService_GetLotDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
