apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalog-db
  namespace: mtv-erp
spec:
  serviceName: catalog-db
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: catalog-db-credentials
          volumeMounts:
            - name: catalog-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: catalog-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
