// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type DeactivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductRequest) Reset() {
	*x = DeactivateProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductRequest) ProtoMessage() {}

func (x *DeactivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *DeactivateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductResponse) Reset() {
	*x = DeactivateProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductResponse) ProtoMessage() {}

func (x *DeactivateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductResponse.ProtoReflect.Descriptor instead.
func (*DeactivateProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UnitOfMeasure struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConversionFactorKg string                 `protobuf:"bytes,3,opt,name=conversion_factor_kg,json=conversionFactorKg,proto3" json:"conversion_factor_kg,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UnitOfMeasure) Reset() {
	*x = UnitOfMeasure{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitOfMeasure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitOfMeasure) ProtoMessage() {}

func (x *UnitOfMeasure) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitOfMeasure.ProtoReflect.Descriptor instead.
func (*UnitOfMeasure) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *UnitOfMeasure) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnitOfMeasure) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitOfMeasure) GetConversionFactorKg() string {
	if x != nil {
		return x.ConversionFactorKg
	}
	return ""
}

type CreateUnitOfMeasureRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConversionFactorKg string                 `protobuf:"bytes,2,opt,name=conversion_factor_kg,json=conversionFactorKg,proto3" json:"conversion_factor_kg,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateUnitOfMeasureRequest) Reset() {
	*x = CreateUnitOfMeasureRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnitOfMeasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnitOfMeasureRequest) ProtoMessage() {}

func (x *CreateUnitOfMeasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnitOfMeasureRequest.ProtoReflect.Descriptor instead.
func (*CreateUnitOfMeasureRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUnitOfMeasureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUnitOfMeasureRequest) GetConversionFactorKg() string {
	if x != nil {
		return x.ConversionFactorKg
	}
	return ""
}

type ListUnitsOfMeasureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUnitsOfMeasureRequest) Reset() {
	*x = ListUnitsOfMeasureRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUnitsOfMeasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUnitsOfMeasureRequest) ProtoMessage() {}

func (x *ListUnitsOfMeasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUnitsOfMeasureRequest.ProtoReflect.Descriptor instead.
func (*ListUnitsOfMeasureRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

type ListUnitsOfMeasureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*UnitOfMeasure       `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUnitsOfMeasureResponse) Reset() {
	*x = ListUnitsOfMeasureResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUnitsOfMeasureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUnitsOfMeasureResponse) ProtoMessage() {}

func (x *ListUnitsOfMeasureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUnitsOfMeasureResponse.ProtoReflect.Descriptor instead.
func (*ListUnitsOfMeasureResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *ListUnitsOfMeasureResponse) GetUnits() []*UnitOfMeasure {
	if x != nil {
		return x.Units
	}
	return nil
}

type CreateUnitOfMeasureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitOfMeasure *UnitOfMeasure         `protobuf:"bytes,1,opt,name=unit_of_measure,json=unitOfMeasure,proto3" json:"unit_of_measure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUnitOfMeasureResponse) Reset() {
	*x = CreateUnitOfMeasureResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnitOfMeasureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnitOfMeasureResponse) ProtoMessage() {}

func (x *CreateUnitOfMeasureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnitOfMeasureResponse.ProtoReflect.Descriptor instead.
func (*CreateUnitOfMeasureResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUnitOfMeasureResponse) GetUnitOfMeasure() *UnitOfMeasure {
	if x != nil {
		return x.UnitOfMeasure
	}
	return nil
}

type ConvertToKgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertToKgRequest) Reset() {
	*x = ConvertToKgRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertToKgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertToKgRequest) ProtoMessage() {}

func (x *ConvertToKgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertToKgRequest.ProtoReflect.Descriptor instead.
func (*ConvertToKgRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *ConvertToKgRequest) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ConvertToKgRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type ConvertToKgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kg            string                 `protobuf:"bytes,1,opt,name=kg,proto3" json:"kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertToKgResponse) Reset() {
	*x = ConvertToKgResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertToKgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertToKgResponse) ProtoMessage() {}

func (x *ConvertToKgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertToKgResponse.ProtoReflect.Descriptor instead.
func (*ConvertToKgResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *ConvertToKgResponse) GetKg() string {
	if x != nil {
		return x.Kg
	}
	return ""
}

type ConvertFromKgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Kg            string                 `protobuf:"bytes,2,opt,name=kg,proto3" json:"kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertFromKgRequest) Reset() {
	*x = ConvertFromKgRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertFromKgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertFromKgRequest) ProtoMessage() {}

func (x *ConvertFromKgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertFromKgRequest.ProtoReflect.Descriptor instead.
func (*ConvertFromKgRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *ConvertFromKgRequest) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ConvertFromKgRequest) GetKg() string {
	if x != nil {
		return x.Kg
	}
	return ""
}

type ConvertFromKgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      string                 `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertFromKgResponse) Reset() {
	*x = ConvertFromKgResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertFromKgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertFromKgResponse) ProtoMessage() {}

func (x *ConvertFromKgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertFromKgResponse.ProtoReflect.Descriptor instead.
func (*ConvertFromKgResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *ConvertFromKgResponse) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"E\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"*\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13ListProductsRequest\"G\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.catalog.v1.ProductR\bproducts\"*\n" +
	"\x18DeactivateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeactivateProductResponse\"F\n" +
	"\x15CreateProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.catalog.v1.ProductR\aproduct\"e\n" +
	"\rUnitOfMeasure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x14conversion_factor_kg\x18\x03 \x01(\tR\x12conversionFactorKg\"b\n" +
	"\x1aCreateUnitOfMeasureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x14conversion_factor_kg\x18\x02 \x01(\tR\x12conversionFactorKg\"\x1b\n" +
	"\x19ListUnitsOfMeasureRequest\"M\n" +
	"\x1aListUnitsOfMeasureResponse\x12/\n" +
	"\x05units\x18\x01 \x03(\v2\x19.catalog.v1.UnitOfMeasureR\x05units\"`\n" +
	"\x1bCreateUnitOfMeasureResponse\x12A\n" +
	"\x0funit_of_measure\x18\x01 \x01(\v2\x19.catalog.v1.UnitOfMeasureR\runitOfMeasure\"I\n" +
	"\x12ConvertToKgRequest\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"%\n" +
	"\x13ConvertToKgResponse\x12\x0e\n" +
	"\x02kg\x18\x01 \x01(\tR\x02kg\"?\n" +
	"\x14ConvertFromKgRequest\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\x0e\n" +
	"\x02kg\x18\x02 \x01(\tR\x02kg\"3\n" +
	"\x15ConvertFromKgResponse\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\tR\bquantity2\x8e\x05\n" +
	"\x0eCatalogService\x12T\n" +
	"\rCreateProduct\x12 .catalog.v1.CreateProductRequest\x1a!.catalog.v1.CreateProductResponse\x12Q\n" +
	"\fListProducts\x12\x1f.catalog.v1.ListProductsRequest\x1a .catalog.v1.ListProductsResponse\x12`\n" +
	"\x11DeactivateProduct\x12$.catalog.v1.DeactivateProductRequest\x1a%.catalog.v1.DeactivateProductResponse\x12f\n" +
	"\x13CreateUnitOfMeasure\x12&.catalog.v1.CreateUnitOfMeasureRequest\x1a'.catalog.v1.CreateUnitOfMeasureResponse\x12c\n" +
	"\x12ListUnitsOfMeasure\x12%.catalog.v1.ListUnitsOfMeasureRequest\x1a&.catalog.v1.ListUnitsOfMeasureResponse\x12N\n" +
	"\vConvertToKg\x12\x1e.catalog.v1.ConvertToKgRequest\x1a\x1f.catalog.v1.ConvertToKgResponse\x12T\n" +
	"\rConvertFromKg\x12 .catalog.v1.ConvertFromKgRequest\x1a!.catalog.v1.ConvertFromKgResponseB:Z8mtv-erp/catalog-service/internal/pb/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(*Product)(nil),                     // 0: catalog.v1.Product
	(*CreateProductRequest)(nil),        // 1: catalog.v1.CreateProductRequest
	(*ListProductsRequest)(nil),         // 2: catalog.v1.ListProductsRequest
	(*ListProductsResponse)(nil),        // 3: catalog.v1.ListProductsResponse
	(*DeactivateProductRequest)(nil),    // 4: catalog.v1.DeactivateProductRequest
	(*DeactivateProductResponse)(nil),   // 5: catalog.v1.DeactivateProductResponse
	(*CreateProductResponse)(nil),       // 6: catalog.v1.CreateProductResponse
	(*UnitOfMeasure)(nil),               // 7: catalog.v1.UnitOfMeasure
	(*CreateUnitOfMeasureRequest)(nil),  // 8: catalog.v1.CreateUnitOfMeasureRequest
	(*ListUnitsOfMeasureRequest)(nil),   // 9: catalog.v1.ListUnitsOfMeasureRequest
	(*ListUnitsOfMeasureResponse)(nil),  // 10: catalog.v1.ListUnitsOfMeasureResponse
	(*CreateUnitOfMeasureResponse)(nil), // 11: catalog.v1.CreateUnitOfMeasureResponse
	(*ConvertToKgRequest)(nil),          // 12: catalog.v1.ConvertToKgRequest
	(*ConvertToKgResponse)(nil),         // 13: catalog.v1.ConvertToKgResponse
	(*ConvertFromKgRequest)(nil),        // 14: catalog.v1.ConvertFromKgRequest
	(*ConvertFromKgResponse)(nil),       // 15: catalog.v1.ConvertFromKgResponse
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.ListProductsResponse.products:type_name -> catalog.v1.Product
	0,  // 1: catalog.v1.CreateProductResponse.product:type_name -> catalog.v1.Product
	7,  // 2: catalog.v1.ListUnitsOfMeasureResponse.units:type_name -> catalog.v1.UnitOfMeasure
	7,  // 3: catalog.v1.CreateUnitOfMeasureResponse.unit_of_measure:type_name -> catalog.v1.UnitOfMeasure
	1,  // 4: catalog.v1.CatalogService.CreateProduct:input_type -> catalog.v1.CreateProductRequest
	2,  // 5: catalog.v1.CatalogService.ListProducts:input_type -> catalog.v1.ListProductsRequest
	4,  // 6: catalog.v1.CatalogService.DeactivateProduct:input_type -> catalog.v1.DeactivateProductRequest
	8,  // 7: catalog.v1.CatalogService.CreateUnitOfMeasure:input_type -> catalog.v1.CreateUnitOfMeasureRequest
	9,  // 8: catalog.v1.CatalogService.ListUnitsOfMeasure:input_type -> catalog.v1.ListUnitsOfMeasureRequest
	12, // 9: catalog.v1.CatalogService.ConvertToKg:input_type -> catalog.v1.ConvertToKgRequest
	14, // 10: catalog.v1.CatalogService.ConvertFromKg:input_type -> catalog.v1.ConvertFromKgRequest
	6,  // 11: catalog.v1.CatalogService.CreateProduct:output_type -> catalog.v1.CreateProductResponse
	3,  // 12: catalog.v1.CatalogService.ListProducts:output_type -> catalog.v1.ListProductsResponse
	5,  // 13: catalog.v1.CatalogService.DeactivateProduct:output_type -> catalog.v1.DeactivateProductResponse
	11, // 14: catalog.v1.CatalogService.CreateUnitOfMeasure:output_type -> catalog.v1.CreateUnitOfMeasureResponse
	10, // 15: catalog.v1.CatalogService.ListUnitsOfMeasure:output_type -> catalog.v1.ListUnitsOfMeasureResponse
	13, // 16: catalog.v1.CatalogService.ConvertToKg:output_type -> catalog.v1.ConvertToKgResponse
	15, // 17: catalog.v1.CatalogService.ConvertFromKg:output_type -> catalog.v1.ConvertFromKgResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
