apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: mtv-erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/tiagogdella/catalog-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: catalog-service-config
            - secretRef:
                name: catalog-service-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
      imagePullSecrets:
        - name: ghcr-secret

