// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: purchasing/v1/purchasing.proto

package purchasingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchaseItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UnitId        string                 `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Safra         string                 `protobuf:"bytes,3,opt,name=safra,proto3" json:"safra,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseItemInput) Reset() {
	*x = PurchaseItemInput{}
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseItemInput) ProtoMessage() {}

func (x *PurchaseItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseItemInput.ProtoReflect.Descriptor instead.
func (*PurchaseItemInput) Descriptor() ([]byte, []int) {
	return file_purchasing_v1_purchasing_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseItemInput) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PurchaseItemInput) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *PurchaseItemInput) GetSafra() string {
	if x != nil {
		return x.Safra
	}
	return ""
}

func (x *PurchaseItemInput) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type PurchaseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UnitId        string                 `protobuf:"bytes,3,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Safra         string                 `protobuf:"bytes,4,opt,name=safra,proto3" json:"safra,omitempty"`
	Quantity      string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LotId         string                 `protobuf:"bytes,6,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseItem) Reset() {
	*x = PurchaseItem{}
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseItem) ProtoMessage() {}

func (x *PurchaseItem) ProtoReflect() protoreflect.Message {
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseItem.ProtoReflect.Descriptor instead.
func (*PurchaseItem) Descriptor() ([]byte, []int) {
	return file_purchasing_v1_purchasing_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PurchaseItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PurchaseItem) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *PurchaseItem) GetSafra() string {
	if x != nil {
		return x.Safra
	}
	return ""
}

func (x *PurchaseItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PurchaseItem) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

type Purchase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SupplierId    string                 `protobuf:"bytes,2,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	InvoiceNumber string                 `protobuf:"bytes,3,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	InvoiceDate   string                 `protobuf:"bytes,4,opt,name=invoice_date,json=invoiceDate,proto3" json:"invoice_date,omitempty"`
	InvoiceValue  string                 `protobuf:"bytes,5,opt,name=invoice_value,json=invoiceValue,proto3" json:"invoice_value,omitempty"`
	Items         []*PurchaseItem        `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchase.ProtoReflect.Descriptor instead.
func (*Purchase) Descriptor() ([]byte, []int) {
	return file_purchasing_v1_purchasing_proto_rawDescGZIP(), []int{2}
}

func (x *Purchase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Purchase) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Purchase) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *Purchase) GetInvoiceDate() string {
	if x != nil {
		return x.InvoiceDate
	}
	return ""
}

func (x *Purchase) GetInvoiceValue() string {
	if x != nil {
		return x.InvoiceValue
	}
	return ""
}

func (x *Purchase) GetItems() []*PurchaseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreatePurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    string                 `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	InvoiceNumber string                 `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	InvoiceDate   string                 `protobuf:"bytes,3,opt,name=invoice_date,json=invoiceDate,proto3" json:"invoice_date,omitempty"`
	InvoiceValue  string                 `protobuf:"bytes,4,opt,name=invoice_value,json=invoiceValue,proto3" json:"invoice_value,omitempty"`
	Items         []*PurchaseItemInput   `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePurchaseRequest) Reset() {
	*x = CreatePurchaseRequest{}
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePurchaseRequest) ProtoMessage() {}

func (x *CreatePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePurchaseRequest.ProtoReflect.Descriptor instead.
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_purchasing_v1_purchasing_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePurchaseRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *CreatePurchaseRequest) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *CreatePurchaseRequest) GetInvoiceDate() string {
	if x != nil {
		return x.InvoiceDate
	}
	return ""
}

func (x *CreatePurchaseRequest) GetInvoiceValue() string {
	if x != nil {
		return x.InvoiceValue
	}
	return ""
}

func (x *CreatePurchaseRequest) GetItems() []*PurchaseItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreatePurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchase      *Purchase              `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePurchaseResponse) Reset() {
	*x = CreatePurchaseResponse{}
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePurchaseResponse) ProtoMessage() {}

func (x *CreatePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchasing_v1_purchasing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePurchaseResponse.ProtoReflect.Descriptor instead.
func (*CreatePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_purchasing_v1_purchasing_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePurchaseResponse) GetPurchase() *Purchase {
	if x != nil {
		return x.Purchase
	}
	return nil
}

var File_purchasing_v1_purchasing_proto protoreflect.FileDescriptor

const file_purchasing_v1_purchasing_proto_rawDesc = "" +
	"\n" +
	"\x1epurchasing/v1/purchasing.proto\x12\rpurchasing.v1\"}\n" +
	"\x11PurchaseItemInput\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\tR\x06unitId\x12\x14\n" +
	"\x05safra\x18\x03 \x01(\tR\x05safra\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\"\x9f\x01\n" +
	"\fPurchaseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x17\n" +
	"\aunit_id\x18\x03 \x01(\tR\x06unitId\x12\x14\n" +
	"\x05safra\x18\x04 \x01(\tR\x05safra\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x15\n" +
	"\x06lot_id\x18\x06 \x01(\tR\x05lotId\"\xdd\x01\n" +
	"\bPurchase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsupplier_id\x18\x02 \x01(\tR\n" +
	"supplierId\x12%\n" +
	"\x0einvoice_number\x18\x03 \x01(\tR\rinvoiceNumber\x12!\n" +
	"\finvoice_date\x18\x04 \x01(\tR\vinvoiceDate\x12#\n" +
	"\rinvoice_value\x18\x05 \x01(\tR\finvoiceValue\x121\n" +
	"\x05items\x18\x06 \x03(\v2\x1b.purchasing.v1.PurchaseItemR\x05items\"\xdf\x01\n" +
	"\x15CreatePurchaseRequest\x12\x1f\n" +
	"\vsupplier_id\x18\x01 \x01(\tR\n" +
	"supplierId\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\x12!\n" +
	"\finvoice_date\x18\x03 \x01(\tR\vinvoiceDate\x12#\n" +
	"\rinvoice_value\x18\x04 \x01(\tR\finvoiceValue\x126\n" +
	"\x05items\x18\x05 \x03(\v2 .purchasing.v1.PurchaseItemInputR\x05items\"M\n" +
	"\x16CreatePurchaseResponse\x123\n" +
	"\bpurchase\x18\x01 \x01(\v2\x17.purchasing.v1.PurchaseR\bpurchase2r\n" +
	"\x11PurchasingService\x12]\n" +
	"\x0eCreatePurchase\x12$.purchasing.v1.CreatePurchaseRequest\x1a%.purchasing.v1.CreatePurchaseResponseBCZAmtv-erp/purchasing-service/internal/pb/purchasing/v1;purchasingv1b\x06proto3"

var (
	file_purchasing_v1_purchasing_proto_rawDescOnce sync.Once
	file_purchasing_v1_purchasing_proto_rawDescData []byte
)

func file_purchasing_v1_purchasing_proto_rawDescGZIP() []byte {
	file_purchasing_v1_purchasing_proto_rawDescOnce.Do(func() {
		file_purchasing_v1_purchasing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_purchasing_v1_purchasing_proto_rawDesc), len(file_purchasing_v1_purchasing_proto_rawDesc)))
	})
	return file_purchasing_v1_purchasing_proto_rawDescData
}

var file_purchasing_v1_purchasing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_purchasing_v1_purchasing_proto_goTypes = []any{
	(*PurchaseItemInput)(nil),      // 0: purchasing.v1.PurchaseItemInput
	(*PurchaseItem)(nil),           // 1: purchasing.v1.PurchaseItem
	(*Purchase)(nil),               // 2: purchasing.v1.Purchase
	(*CreatePurchaseRequest)(nil),  // 3: purchasing.v1.CreatePurchaseRequest
	(*CreatePurchaseResponse)(nil), // 4: purchasing.v1.CreatePurchaseResponse
}
var file_purchasing_v1_purchasing_proto_depIdxs = []int32{
	1, // 0: purchasing.v1.Purchase.items:type_name -> purchasing.v1.PurchaseItem
	0, // 1: purchasing.v1.CreatePurchaseRequest.items:type_name -> purchasing.v1.PurchaseItemInput
	2, // 2: purchasing.v1.CreatePurchaseResponse.purchase:type_name -> purchasing.v1.Purchase
	3, // 3: purchasing.v1.PurchasingService.CreatePurchase:input_type -> purchasing.v1.CreatePurchaseRequest
	4, // 4: purchasing.v1.PurchasingService.CreatePurchase:output_type -> purchasing.v1.CreatePurchaseResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_purchasing_v1_purchasing_proto_init() }
func file_purchasing_v1_purchasing_proto_init() {
	if File_purchasing_v1_purchasing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_purchasing_v1_purchasing_proto_rawDesc), len(file_purchasing_v1_purchasing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_purchasing_v1_purchasing_proto_goTypes,
		DependencyIndexes: file_purchasing_v1_purchasing_proto_depIdxs,
		MessageInfos:      file_purchasing_v1_purchasing_proto_msgTypes,
	}.Build()
	File_purchasing_v1_purchasing_proto = out.File
	file_purchasing_v1_purchasing_proto_goTypes = nil
	file_purchasing_v1_purchasing_proto_depIdxs = nil
}
