// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: purchasing/v1/purchasing.proto

package purchasingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PurchasingService_CreatePurchase_FullMethodName = "/purchasing.v1.PurchasingService/CreatePurchase"
)

// PurchasingServiceClient is the client API for PurchasingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PurchasingServiceClient interface {
	CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error)
}

type purchasingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPurchasingServiceClient(cc grpc.ClientConnInterface) PurchasingServiceClient {
	return &purchasingServiceClient{cc}
}

func (c *purchasingServiceClient) CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePurchaseResponse)
	err := c.cc.Invoke(ctx, PurchasingService_CreatePurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchasingServiceServer is the server API for PurchasingService service.
// All implementations must embed UnimplementedPurchasingServiceServer
// for forward compatibility.
type PurchasingServiceServer interface {
	CreatePurchase(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error)
	mustEmbedUnimplementedPurchasingServiceServer()
}

// UnimplementedPurchasingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPurchasingServiceServer struct{}

func (UnimplementedPurchasingServiceServer) CreatePurchase(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePurchase not implemented")
}
func (UnimplementedPurchasingServiceServer) mustEmbedUnimplementedPurchasingServiceServer() {}
func (UnimplementedPurchasingServiceServer) testEmbeddedByValue()                           {}

// UnsafePurchasingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PurchasingServiceServer will
// result in compilation errors.
type UnsafePurchasingServiceServer interface {
	mustEmbedUnimplementedPurchasingServiceServer()
}

func RegisterPurchasingServiceServer(s grpc.ServiceRegistrar, srv PurchasingServiceServer) {
	// If the following call panics, it indicates UnimplementedPurchasingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PurchasingService_ServiceDesc, srv)
}

func _PurchasingService_CreatePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchasingServiceServer).CreatePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchasingService_CreatePurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchasingServiceServer).CreatePurchase(ctx, req.(*CreatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PurchasingService_ServiceDesc is the grpc.ServiceDesc for PurchasingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PurchasingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "purchasing.v1.PurchasingService",
	HandlerType: (*PurchasingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePurchase",
			Handler:    _PurchasingService_CreatePurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "purchasing/v1/purchasing.proto",
}
