apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: mtv-erp
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090
