// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type DeactivateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductRequest) Reset() {
	*x = DeactivateProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductRequest) ProtoMessage() {}

func (x *DeactivateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductRequest.ProtoReflect.Descriptor instead.
func (*DeactivateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *DeactivateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateProductResponse) Reset() {
	*x = DeactivateProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateProductResponse) ProtoMessage() {}

func (x *DeactivateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateProductResponse.ProtoReflect.Descriptor instead.
func (*DeactivateProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type Supplier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Document      string                 `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Supplier) Reset() {
	*x = Supplier{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Supplier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supplier) ProtoMessage() {}

func (x *Supplier) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supplier.ProtoReflect.Descriptor instead.
func (*Supplier) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *Supplier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Supplier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Supplier) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *Supplier) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Supplier) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CreateSupplierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Document      string                 `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSupplierRequest) Reset() {
	*x = CreateSupplierRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSupplierRequest) ProtoMessage() {}

func (x *CreateSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSupplierRequest.ProtoReflect.Descriptor instead.
func (*CreateSupplierRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSupplierRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSupplierRequest) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *CreateSupplierRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateSupplierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supplier      *Supplier              `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSupplierResponse) Reset() {
	*x = CreateSupplierResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSupplierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSupplierResponse) ProtoMessage() {}

func (x *CreateSupplierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSupplierResponse.ProtoReflect.Descriptor instead.
func (*CreateSupplierResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSupplierResponse) GetSupplier() *Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type ListSuppliersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSuppliersRequest) Reset() {
	*x = ListSuppliersRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSuppliersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuppliersRequest) ProtoMessage() {}

func (x *ListSuppliersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuppliersRequest.ProtoReflect.Descriptor instead.
func (*ListSuppliersRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

type ListSuppliersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suppliers     []*Supplier            `protobuf:"bytes,1,rep,name=suppliers,proto3" json:"suppliers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSuppliersResponse) Reset() {
	*x = ListSuppliersResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSuppliersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuppliersResponse) ProtoMessage() {}

func (x *ListSuppliersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuppliersResponse.ProtoReflect.Descriptor instead.
func (*ListSuppliersResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *ListSuppliersResponse) GetSuppliers() []*Supplier {
	if x != nil {
		return x.Suppliers
	}
	return nil
}

type DeactivateSupplierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateSupplierRequest) Reset() {
	*x = DeactivateSupplierRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateSupplierRequest) ProtoMessage() {}

func (x *DeactivateSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateSupplierRequest.ProtoReflect.Descriptor instead.
func (*DeactivateSupplierRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *DeactivateSupplierRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateSupplierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateSupplierResponse) Reset() {
	*x = DeactivateSupplierResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateSupplierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateSupplierResponse) ProtoMessage() {}

func (x *DeactivateSupplierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateSupplierResponse.ProtoReflect.Descriptor instead.
func (*DeactivateSupplierResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{15}
}

type GetSupplierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupplierRequest) Reset() {
	*x = GetSupplierRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierRequest) ProtoMessage() {}

func (x *GetSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierRequest.ProtoReflect.Descriptor instead.
func (*GetSupplierRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *GetSupplierRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSupplierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supplier      *Supplier              `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupplierResponse) Reset() {
	*x = GetSupplierResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierResponse) ProtoMessage() {}

func (x *GetSupplierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierResponse.ProtoReflect.Descriptor instead.
func (*GetSupplierResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *GetSupplierResponse) GetSupplier() *Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type UnitOfMeasure struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConversionFactorKg string                 `protobuf:"bytes,3,opt,name=conversion_factor_kg,json=conversionFactorKg,proto3" json:"conversion_factor_kg,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UnitOfMeasure) Reset() {
	*x = UnitOfMeasure{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitOfMeasure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitOfMeasure) ProtoMessage() {}

func (x *UnitOfMeasure) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitOfMeasure.ProtoReflect.Descriptor instead.
func (*UnitOfMeasure) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *UnitOfMeasure) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnitOfMeasure) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitOfMeasure) GetConversionFactorKg() string {
	if x != nil {
		return x.ConversionFactorKg
	}
	return ""
}

type CreateUnitOfMeasureRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConversionFactorKg string                 `protobuf:"bytes,2,opt,name=conversion_factor_kg,json=conversionFactorKg,proto3" json:"conversion_factor_kg,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateUnitOfMeasureRequest) Reset() {
	*x = CreateUnitOfMeasureRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnitOfMeasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnitOfMeasureRequest) ProtoMessage() {}

func (x *CreateUnitOfMeasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnitOfMeasureRequest.ProtoReflect.Descriptor instead.
func (*CreateUnitOfMeasureRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *CreateUnitOfMeasureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUnitOfMeasureRequest) GetConversionFactorKg() string {
	if x != nil {
		return x.ConversionFactorKg
	}
	return ""
}

type ListUnitsOfMeasureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUnitsOfMeasureRequest) Reset() {
	*x = ListUnitsOfMeasureRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUnitsOfMeasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUnitsOfMeasureRequest) ProtoMessage() {}

func (x *ListUnitsOfMeasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUnitsOfMeasureRequest.ProtoReflect.Descriptor instead.
func (*ListUnitsOfMeasureRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{20}
}

type ListUnitsOfMeasureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*UnitOfMeasure       `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUnitsOfMeasureResponse) Reset() {
	*x = ListUnitsOfMeasureResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUnitsOfMeasureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUnitsOfMeasureResponse) ProtoMessage() {}

func (x *ListUnitsOfMeasureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUnitsOfMeasureResponse.ProtoReflect.Descriptor instead.
func (*ListUnitsOfMeasureResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *ListUnitsOfMeasureResponse) GetUnits() []*UnitOfMeasure {
	if x != nil {
		return x.Units
	}
	return nil
}

type CreateUnitOfMeasureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitOfMeasure *UnitOfMeasure         `protobuf:"bytes,1,opt,name=unit_of_measure,json=unitOfMeasure,proto3" json:"unit_of_measure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUnitOfMeasureResponse) Reset() {
	*x = CreateUnitOfMeasureResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUnitOfMeasureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUnitOfMeasureResponse) ProtoMessage() {}

func (x *CreateUnitOfMeasureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUnitOfMeasureResponse.ProtoReflect.Descriptor instead.
func (*CreateUnitOfMeasureResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *CreateUnitOfMeasureResponse) GetUnitOfMeasure() *UnitOfMeasure {
	if x != nil {
		return x.UnitOfMeasure
	}
	return nil
}

type ConvertToKgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertToKgRequest) Reset() {
	*x = ConvertToKgRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertToKgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertToKgRequest) ProtoMessage() {}

func (x *ConvertToKgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertToKgRequest.ProtoReflect.Descriptor instead.
func (*ConvertToKgRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *ConvertToKgRequest) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ConvertToKgRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type ConvertToKgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kg            string                 `protobuf:"bytes,1,opt,name=kg,proto3" json:"kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertToKgResponse) Reset() {
	*x = ConvertToKgResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertToKgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertToKgResponse) ProtoMessage() {}

func (x *ConvertToKgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertToKgResponse.ProtoReflect.Descriptor instead.
func (*ConvertToKgResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{24}
}

func (x *ConvertToKgResponse) GetKg() string {
	if x != nil {
		return x.Kg
	}
	return ""
}

type ConvertFromKgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	Kg            string                 `protobuf:"bytes,2,opt,name=kg,proto3" json:"kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertFromKgRequest) Reset() {
	*x = ConvertFromKgRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertFromKgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertFromKgRequest) ProtoMessage() {}

func (x *ConvertFromKgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertFromKgRequest.ProtoReflect.Descriptor instead.
func (*ConvertFromKgRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{25}
}

func (x *ConvertFromKgRequest) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ConvertFromKgRequest) GetKg() string {
	if x != nil {
		return x.Kg
	}
	return ""
}

type ConvertFromKgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      string                 `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertFromKgResponse) Reset() {
	*x = ConvertFromKgResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertFromKgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertFromKgResponse) ProtoMessage() {}

func (x *ConvertFromKgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertFromKgResponse.ProtoReflect.Descriptor instead.
func (*ConvertFromKgResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{26}
}

func (x *ConvertFromKgResponse) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"E\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"*\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13ListProductsRequest\"G\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.catalog.v1.ProductR\bproducts\"*\n" +
	"\x18DeactivateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeactivateProductResponse\"F\n" +
	"\x15CreateProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.catalog.v1.ProductR\aproduct\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.catalog.v1.ProductR\aproduct\"|\n" +
	"\bSupplier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdocument\x18\x03 \x01(\tR\bdocument\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"a\n" +
	"\x15CreateSupplierRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\tR\bdocument\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"J\n" +
	"\x16CreateSupplierResponse\x120\n" +
	"\bsupplier\x18\x01 \x01(\v2\x14.catalog.v1.SupplierR\bsupplier\"\x16\n" +
	"\x14ListSuppliersRequest\"K\n" +
	"\x15ListSuppliersResponse\x122\n" +
	"\tsuppliers\x18\x01 \x03(\v2\x14.catalog.v1.SupplierR\tsuppliers\"+\n" +
	"\x19DeactivateSupplierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\x1aDeactivateSupplierResponse\"$\n" +
	"\x12GetSupplierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x13GetSupplierResponse\x120\n" +
	"\bsupplier\x18\x01 \x01(\v2\x14.catalog.v1.SupplierR\bsupplier\"e\n" +
	"\rUnitOfMeasure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x14conversion_factor_kg\x18\x03 \x01(\tR\x12conversionFactorKg\"b\n" +
	"\x1aCreateUnitOfMeasureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x14conversion_factor_kg\x18\x02 \x01(\tR\x12conversionFactorKg\"\x1b\n" +
	"\x19ListUnitsOfMeasureRequest\"M\n" +
	"\x1aListUnitsOfMeasureResponse\x12/\n" +
	"\x05units\x18\x01 \x03(\v2\x19.catalog.v1.UnitOfMeasureR\x05units\"`\n" +
	"\x1bCreateUnitOfMeasureResponse\x12A\n" +
	"\x0funit_of_measure\x18\x01 \x01(\v2\x19.catalog.v1.UnitOfMeasureR\runitOfMeasure\"I\n" +
	"\x12ConvertToKgRequest\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"%\n" +
	"\x13ConvertToKgResponse\x12\x0e\n" +
	"\x02kg\x18\x01 \x01(\tR\x02kg\"?\n" +
	"\x14ConvertFromKgRequest\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12\x0e\n" +
	"\x02kg\x18\x02 \x01(\tR\x02kg\"3\n" +
	"\x15ConvertFromKgResponse\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\tR\bquantity2\xbf\b\n" +
	"\x0eCatalogService\x12T\n" +
	"\rCreateProduct\x12 .catalog.v1.CreateProductRequest\x1a!.catalog.v1.CreateProductResponse\x12Q\n" +
	"\fListProducts\x12\x1f.catalog.v1.ListProductsRequest\x1a .catalog.v1.ListProductsResponse\x12`\n" +
	"\x11DeactivateProduct\x12$.catalog.v1.DeactivateProductRequest\x1a%.catalog.v1.DeactivateProductResponse\x12K\n" +
	"\n" +
	"GetProduct\x12\x1d.catalog.v1.GetProductRequest\x1a\x1e.catalog.v1.GetProductResponse\x12W\n" +
	"\x0eCreateSupplier\x12!.catalog.v1.CreateSupplierRequest\x1a\".catalog.v1.CreateSupplierResponse\x12T\n" +
	"\rListSuppliers\x12 .catalog.v1.ListSuppliersRequest\x1a!.catalog.v1.ListSuppliersResponse\x12c\n" +
	"\x12DeactivateSupplier\x12%.catalog.v1.DeactivateSupplierRequest\x1a&.catalog.v1.DeactivateSupplierResponse\x12N\n" +
	"\vGetSupplier\x12\x1e.catalog.v1.GetSupplierRequest\x1a\x1f.catalog.v1.GetSupplierResponse\x12f\n" +
	"\x13CreateUnitOfMeasure\x12&.catalog.v1.CreateUnitOfMeasureRequest\x1a'.catalog.v1.CreateUnitOfMeasureResponse\x12c\n" +
	"\x12ListUnitsOfMeasure\x12%.catalog.v1.ListUnitsOfMeasureRequest\x1a&.catalog.v1.ListUnitsOfMeasureResponse\x12N\n" +
	"\vConvertToKg\x12\x1e.catalog.v1.ConvertToKgRequest\x1a\x1f.catalog.v1.ConvertToKgResponse\x12T\n" +
	"\rConvertFromKg\x12 .catalog.v1.ConvertFromKgRequest\x1a!.catalog.v1.ConvertFromKgResponseB=Z;mtv-erp/purchasing-service/internal/pb/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(*Product)(nil),                     // 0: catalog.v1.Product
	(*CreateProductRequest)(nil),        // 1: catalog.v1.CreateProductRequest
	(*ListProductsRequest)(nil),         // 2: catalog.v1.ListProductsRequest
	(*ListProductsResponse)(nil),        // 3: catalog.v1.ListProductsResponse
	(*DeactivateProductRequest)(nil),    // 4: catalog.v1.DeactivateProductRequest
	(*DeactivateProductResponse)(nil),   // 5: catalog.v1.DeactivateProductResponse
	(*CreateProductResponse)(nil),       // 6: catalog.v1.CreateProductResponse
	(*GetProductRequest)(nil),           // 7: catalog.v1.GetProductRequest
	(*GetProductResponse)(nil),          // 8: catalog.v1.GetProductResponse
	(*Supplier)(nil),                    // 9: catalog.v1.Supplier
	(*CreateSupplierRequest)(nil),       // 10: catalog.v1.CreateSupplierRequest
	(*CreateSupplierResponse)(nil),      // 11: catalog.v1.CreateSupplierResponse
	(*ListSuppliersRequest)(nil),        // 12: catalog.v1.ListSuppliersRequest
	(*ListSuppliersResponse)(nil),       // 13: catalog.v1.ListSuppliersResponse
	(*DeactivateSupplierRequest)(nil),   // 14: catalog.v1.DeactivateSupplierRequest
	(*DeactivateSupplierResponse)(nil),  // 15: catalog.v1.DeactivateSupplierResponse
	(*GetSupplierRequest)(nil),          // 16: catalog.v1.GetSupplierRequest
	(*GetSupplierResponse)(nil),         // 17: catalog.v1.GetSupplierResponse
	(*UnitOfMeasure)(nil),               // 18: catalog.v1.UnitOfMeasure
	(*CreateUnitOfMeasureRequest)(nil),  // 19: catalog.v1.CreateUnitOfMeasureRequest
	(*ListUnitsOfMeasureRequest)(nil),   // 20: catalog.v1.ListUnitsOfMeasureRequest
	(*ListUnitsOfMeasureResponse)(nil),  // 21: catalog.v1.ListUnitsOfMeasureResponse
	(*CreateUnitOfMeasureResponse)(nil), // 22: catalog.v1.CreateUnitOfMeasureResponse
	(*ConvertToKgRequest)(nil),          // 23: catalog.v1.ConvertToKgRequest
	(*ConvertToKgResponse)(nil),         // 24: catalog.v1.ConvertToKgResponse
	(*ConvertFromKgRequest)(nil),        // 25: catalog.v1.ConvertFromKgRequest
	(*ConvertFromKgResponse)(nil),       // 26: catalog.v1.ConvertFromKgResponse
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.ListProductsResponse.products:type_name -> catalog.v1.Product
	0,  // 1: catalog.v1.CreateProductResponse.product:type_name -> catalog.v1.Product
	0,  // 2: catalog.v1.GetProductResponse.product:type_name -> catalog.v1.Product
	9,  // 3: catalog.v1.CreateSupplierResponse.supplier:type_name -> catalog.v1.Supplier
	9,  // 4: catalog.v1.ListSuppliersResponse.suppliers:type_name -> catalog.v1.Supplier
	9,  // 5: catalog.v1.GetSupplierResponse.supplier:type_name -> catalog.v1.Supplier
	18, // 6: catalog.v1.ListUnitsOfMeasureResponse.units:type_name -> catalog.v1.UnitOfMeasure
	18, // 7: catalog.v1.CreateUnitOfMeasureResponse.unit_of_measure:type_name -> catalog.v1.UnitOfMeasure
	1,  // 8: catalog.v1.CatalogService.CreateProduct:input_type -> catalog.v1.CreateProductRequest
	2,  // 9: catalog.v1.CatalogService.ListProducts:input_type -> catalog.v1.ListProductsRequest
	4,  // 10: catalog.v1.CatalogService.DeactivateProduct:input_type -> catalog.v1.DeactivateProductRequest
	7,  // 11: catalog.v1.CatalogService.GetProduct:input_type -> catalog.v1.GetProductRequest
	10, // 12: catalog.v1.CatalogService.CreateSupplier:input_type -> catalog.v1.CreateSupplierRequest
	12, // 13: catalog.v1.CatalogService.ListSuppliers:input_type -> catalog.v1.ListSuppliersRequest
	14, // 14: catalog.v1.CatalogService.DeactivateSupplier:input_type -> catalog.v1.DeactivateSupplierRequest
	16, // 15: catalog.v1.CatalogService.GetSupplier:input_type -> catalog.v1.GetSupplierRequest
	19, // 16: catalog.v1.CatalogService.CreateUnitOfMeasure:input_type -> catalog.v1.CreateUnitOfMeasureRequest
	20, // 17: catalog.v1.CatalogService.ListUnitsOfMeasure:input_type -> catalog.v1.ListUnitsOfMeasureRequest
	23, // 18: catalog.v1.CatalogService.ConvertToKg:input_type -> catalog.v1.ConvertToKgRequest
	25, // 19: catalog.v1.CatalogService.ConvertFromKg:input_type -> catalog.v1.ConvertFromKgRequest
	6,  // 20: catalog.v1.CatalogService.CreateProduct:output_type -> catalog.v1.CreateProductResponse
	3,  // 21: catalog.v1.CatalogService.ListProducts:output_type -> catalog.v1.ListProductsResponse
	5,  // 22: catalog.v1.CatalogService.DeactivateProduct:output_type -> catalog.v1.DeactivateProductResponse
	8,  // 23: catalog.v1.CatalogService.GetProduct:output_type -> catalog.v1.GetProductResponse
	11, // 24: catalog.v1.CatalogService.CreateSupplier:output_type -> catalog.v1.CreateSupplierResponse
	13, // 25: catalog.v1.CatalogService.ListSuppliers:output_type -> catalog.v1.ListSuppliersResponse
	15, // 26: catalog.v1.CatalogService.DeactivateSupplier:output_type -> catalog.v1.DeactivateSupplierResponse
	17, // 27: catalog.v1.CatalogService.GetSupplier:output_type -> catalog.v1.GetSupplierResponse
	22, // 28: catalog.v1.CatalogService.CreateUnitOfMeasure:output_type -> catalog.v1.CreateUnitOfMeasureResponse
	21, // 29: catalog.v1.CatalogService.ListUnitsOfMeasure:output_type -> catalog.v1.ListUnitsOfMeasureResponse
	24, // 30: catalog.v1.CatalogService.ConvertToKg:output_type -> catalog.v1.ConvertToKgResponse
	26, // 31: catalog.v1.CatalogService.ConvertFromKg:output_type -> catalog.v1.ConvertFromKgResponse
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
